global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/prometheus'
    static_configs:
        - targets: [ 'host.docker.internal:51270' ]

